import React from "react";
import ServiceBlock from "./ServiceBlock";

function Services(props) {
  const services = [
    {
      id: 1,
      title: "Safety Score",
      des: "Our smart AI predicts your financial safety and stability on availing the loan in the form of a simple percentage.",
      img: "/img/service1.png",
    },
    {
      id: 2,
      title: "Investment Suggestions",
      des: "Using the Safety Score, our AI also suggests investment plans to improve your Safety Score.",
      img: "/img/service2.png",
    },
    {
      id: 3,
      title: "Smart Graphs",
      des: "Graphs generated by AI suggests the most preferable loan plans for your financial variables.",
      img: "/img/service3.png",
    },
  ];
  return (
    <section id="Services" className="h-fit py-[70px] bg-gray-50 -z-50 shadow-2xl">
      <h1 className="block uppercase tracking-wide text-gray-700 text-3xl text-center font-bold mb-6">
        Services
      </h1>
      <div className="my-4 mx-2 grid grid-cols-1 md:grid-cols-3 gap-5">
        {services.map((item) => (
          <ServiceBlock
            key={item.id}
            id={item.id}
            title={item.title}
            des={item.des}
            imgLink={item.img}
          />
        ))}
      </div>
    </section>
  );
}

export default Services;
